application: zeta-mu-points
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

handlers:
#Static Handlers
- url: /static
  static_dir: static
- url: /bower_components
  static_dir: bower_components
- url: /admin
  secure: always
  script: admin_controller.app
  login: admin
- url: /admin/.*
  secure: always
  script: admin_controller.app
  login: admin
- url: /.*
  secure: always
  script: index_controller.app
  login: required

#We need webapp2 for the web framework and jinja handles our HTML templates
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
